name: Run tests
on: push
jobs:
  run-tests:
    name: Runs test suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "22.x"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: timeout 10s pnpm test
